// Generated by scripts/embed-migrations.ts. Do not edit directly.

import type { MigrationMeta } from "drizzle-orm/migrator";

interface OperationalMigration extends MigrationMeta {
  readonly idx: number;
  readonly tag: string;
}

export const operationalMigrations = [
  {
    "bps": true,
    "folderMillis": 1783975442221,
    "hash": "16622c08007a9087a65d781f68c222fa15799e95b0332c4a4d932884e0c48bbe",
    "idx": 0,
    "sql": [
      "CREATE TABLE IF NOT EXISTS `delivery_objects` (\n\t`ciphertext_hash` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`deleted_at` integer,\n\t`expires_at` integer NOT NULL\n);\n",
      "\nCREATE INDEX IF NOT EXISTS `delivery_objects_expiry_idx` ON `delivery_objects` (`deleted_at`,`expires_at`);",
      "\nCREATE TABLE IF NOT EXISTS `manifest_outbox` (\n\t`attempt_count` integer DEFAULT 0 NOT NULL,\n\t`client_manifest_id` text PRIMARY KEY NOT NULL,\n\t`committed_at` integer,\n\t`created_at` integer NOT NULL,\n\t`idempotency_key` text NOT NULL,\n\t`last_attempt_at` integer,\n\t`safe_error_code` text,\n\t`signed_manifest_json` text NOT NULL,\n\t`trace_id` text NOT NULL,\n\tFOREIGN KEY (`trace_id`) REFERENCES `trace_lifecycle`(`trace_id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX IF NOT EXISTS `manifest_outbox_idempotency_idx` ON `manifest_outbox` (`idempotency_key`);",
      "\nCREATE INDEX IF NOT EXISTS `manifest_outbox_pending_idx` ON `manifest_outbox` (`committed_at`,`created_at`);",
      "\nCREATE TABLE IF NOT EXISTS `manifest_tombstones` (\n\t`client_manifest_id` text PRIMARY KEY NOT NULL,\n\t`safe_reason_code` text NOT NULL,\n\t`tombstoned_at` integer NOT NULL\n);\n",
      "\nCREATE TABLE IF NOT EXISTS `multipart_uploads` (\n\t`ciphertext_hash` text PRIMARY KEY NOT NULL,\n\t`parts_json` text DEFAULT '[]' NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`upload_id` text NOT NULL\n);\n",
      "\nCREATE TABLE IF NOT EXISTS `operational_state` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`value` text NOT NULL\n);\n",
      "\nCREATE TABLE IF NOT EXISTS `safe_audit_events` (\n\t`action` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`safe_details` text NOT NULL\n);\n",
      "\nCREATE TABLE IF NOT EXISTS `safe_events` (\n\t`created_at` integer NOT NULL,\n\t`kind` text NOT NULL,\n\t`safe_details` text NOT NULL,\n\t`sequence` integer PRIMARY KEY AUTOINCREMENT NOT NULL\n);\n",
      "\nCREATE INDEX IF NOT EXISTS `safe_events_created_idx` ON `safe_events` (`created_at`);",
      "\nCREATE TABLE IF NOT EXISTS `trace_lifecycle` (\n\t`canonical_hash` text,\n\t`captured_at` text NOT NULL,\n\t`ciphertext_hash` text,\n\t`client_manifest_id` text,\n\t`failure_stage` text,\n\t`safe_error_code` text,\n\t`state` text NOT NULL,\n\t`trace_id` text PRIMARY KEY NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tCONSTRAINT \"trace_lifecycle_state_check\" CHECK(\"trace_lifecycle\".\"state\" in ('observed', 'encrypted', 'manifest_pending', 'committed', 'failed'))\n);\n"
    ],
    "tag": "0000_early_cardiac"
  }
] satisfies OperationalMigration[];
