blank_issues_enabled: false
contact_links:
  - name: Private security report
    url: https://github.com/smashah/traicer/security/advisories/new
    about: Report vulnerabilities or anything that may contain sensitive data privately.
