import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

interface Journal {
  readonly entries: readonly {
    readonly breakpoints: boolean;
    readonly idx: number;
    readonly tag: string;
    readonly when: number;
  }[];
}

const packageRoot = new URL("../", import.meta.url);
const journal = JSON.parse(
  readFileSync(new URL("migrations/meta/_journal.json", packageRoot), "utf8")
) as Journal;

const entries = [...journal.entries].sort((left, right) => left.idx - right.idx);
for (const [position, entry] of entries.entries()) {
  const previous = entries[position - 1];
  if (entry.idx !== position) {
    throw new Error(`Migration journal index ${entry.idx} is not contiguous at ${position}`);
  }
  if (previous && entry.when <= previous.when) {
    throw new Error(`Migration ${entry.tag} does not have an increasing timestamp`);
  }
  if (entries.some((candidate, index) => index !== position && candidate.tag === entry.tag)) {
    throw new Error(`Migration tag ${entry.tag} is duplicated`);
  }
}

const migrations = entries.map((entry) => {
  const query = readFileSync(
    new URL(`migrations/${entry.tag}.sql`, packageRoot),
    "utf8"
  );
  return {
    bps: entry.breakpoints,
    folderMillis: entry.when,
    hash: createHash("sha256").update(query).digest("hex"),
    idx: entry.idx,
    sql: query.split("--> statement-breakpoint"),
    tag: entry.tag,
  };
});

const source = `// Generated by scripts/embed-migrations.ts. Do not edit directly.\n\nimport type { MigrationMeta } from "drizzle-orm/migrator";\n\ninterface OperationalMigration extends MigrationMeta {\n  readonly idx: number;\n  readonly tag: string;\n}\n\nexport const operationalMigrations = ${JSON.stringify(migrations, null, 2)} satisfies OperationalMigration[];\n`;
const output = new URL("src/generated-migrations.ts", packageRoot);

if (process.argv.includes("--check")) {
  if (readFileSync(output, "utf8") !== source) {
    throw new Error("Embedded migrations are stale; run pnpm db:embed");
  }
} else {
  writeFileSync(output, source);
}
