import { access, chmod, mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { bytesToBase64Url, generateDeviceSigningKeyPair } from "@traice/crypto";

import { parseCloudflareAccountId, type CloudflareAccountId } from "./cloudflare";
import type { Provider, StorageProvider, TraicerConfig } from "./config";

export interface InitOptions {
  readonly accountId?: CloudflareAccountId;
  readonly bucket?: string;
  readonly directory: string;
  readonly endpoint?: string;
  readonly marketplaceApiBaseUrl: string;
  readonly provider?: Provider;
  readonly region: string;
  readonly storage: StorageProvider;
}

export interface ScaffoldDependencies {
  readonly encryptSecret: (value: string) => Promise<string>;
  readonly generateSigningKeyPair?: typeof generateDeviceSigningKeyPair;
  readonly randomBytes?: (length: number) => Uint8Array;
  readonly randomUuid?: () => string;
}

const exists = async (path: string) => access(path).then(() => true, () => false);

const randomBytes = (length: number): Uint8Array => crypto.getRandomValues(new Uint8Array(length));

export const varlockCommand = (...args: string[]): string[] => {
  const entrypoint = Bun.resolveSync("varlock", import.meta.dir);
  return [process.execPath, resolve(entrypoint, "..", "..", "bin", "cli.js"), ...args];
};

const envSchema = `# Traicer runtime secrets — values belong in .env.local or a Varlock provider.\n# @defaultRequired=infer\n# @defaultSensitive=false\n\n# @required @sensitive\nTRAICER_MARKETPLACE_CREDENTIAL=\n\n# @required @sensitive\nTRAICER_STORAGE_ACCESS_KEY_ID=\n# @required @sensitive\nTRAICER_STORAGE_SECRET_ACCESS_KEY=\n# @optional @sensitive\nTRAICER_STORAGE_SESSION_TOKEN=\n\n# Device-local capabilities generated by traicer init.\n# @required @sensitive\nTRAICER_CONTROL_TOKEN=\n# @required @sensitive\nTRAICER_SIGNING_PRIVATE_KEY=\n# @required @sensitive\nTRAICER_VAULT_KEY=\n# @required @sensitive\nTRAICER_PROJECT_MAPPING_KEY=\n`;

const infraPackage = `${JSON.stringify({
  name: "traicer-storage-infra",
  packageManager: "pnpm@10.28.1",
  private: true,
  scripts: { alchemy: "alchemy" },
  dependencies: {
    "@effect/platform-bun": "4.0.0-beta.98",
    "@effect/platform-node": "4.0.0-beta.98",
    alchemy: "2.0.0-beta.61",
    effect: "4.0.0-beta.98",
  },
}, null, 2)}\n`;

const infraWorkspace = `onlyBuiltDependencies:\n  - msgpackr-extract\n  - workerd\nminimumReleaseAgeExclude:\n  - '@effect/platform-bun@4.0.0-beta.98'\n  - '@effect/platform-node@4.0.0-beta.98'\n  - '@effect/platform-node-shared@4.0.0-beta.98'\n  - 'effect@4.0.0-beta.98'\n`;

const alchemyStack = (
  storage: StorageProvider,
  bucket: string,
  accountId?: CloudflareAccountId
): string | undefined => {
  if (storage === "existing-s3") return undefined;
  if (storage === "cloudflare-r2") {
    if (!accountId) throw new Error("Cloudflare R2 setup requires --account-id");
    return `import * as Alchemy from "alchemy";\nimport * as Cloudflare from "alchemy/Cloudflare";\nimport * as Effect from "effect/Effect";\n\nprocess.env.CLOUDFLARE_ACCOUNT_ID ??= ${JSON.stringify(accountId)};\n\nexport default Alchemy.Stack(\n  "TraicerStorage",\n  { providers: Cloudflare.providers(), state: Cloudflare.state() },\n  Effect.gen(function* () {\n    const traces = yield* Cloudflare.R2.Bucket("SellerTraces", { name: ${JSON.stringify(bucket)} });\n    return { bucketName: traces.bucketName };\n  }),\n);\n`;
  }
  return `import * as Alchemy from "alchemy";\nimport * as AWS from "alchemy/AWS";\nimport * as S3 from "alchemy/AWS/S3";\nimport * as Effect from "effect/Effect";\n\nexport default Alchemy.Stack(\n  "TraicerStorage",\n  { providers: AWS.providers(), state: AWS.state() },\n  Effect.gen(function* () {\n    const traces = yield* S3.Bucket("SellerTraces", {\n      bucketName: ${JSON.stringify(bucket)},\n      encryption: { sseAlgorithm: "AES256" },\n      publicAccessBlock: {\n        blockPublicAcls: true,\n        blockPublicPolicy: true,\n        ignorePublicAcls: true,\n        restrictPublicBuckets: true,\n      },\n      versioning: "Enabled",\n    });\n    return { bucketName: traces.bucketName };\n  }),\n);\n`;
};

const resolveStorage = (options: InitOptions, deviceId: string) => {
  const bucket = options.bucket ?? `traicer-${deviceId.slice(0, 8)}`;
  if (options.storage === "cloudflare-r2") {
    if (!options.accountId) throw new Error("Cloudflare R2 setup requires --account-id");
    const accountId = parseCloudflareAccountId(options.accountId);
    return {
      addressingStyle: "path" as const,
      bucket,
      endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
      signingRegion: "auto",
    };
  }
  if (options.storage === "aws-s3") {
    return {
      addressingStyle: "virtual_hosted" as const,
      bucket,
      endpoint: `https://s3.${options.region}.amazonaws.com`,
      signingRegion: options.region,
    };
  }
  if (!options.endpoint || !options.bucket) {
    throw new Error("Existing S3 setup requires --endpoint and --bucket");
  }
  return {
    addressingStyle: "path" as const,
    bucket: options.bucket,
    endpoint: options.endpoint,
    signingRegion: options.region,
  };
};

export const createScaffold = async (
  options: InitOptions,
  dependencies: ScaffoldDependencies
): Promise<{ readonly config: TraicerConfig; readonly infrastructureDirectory?: string }> => {
  const directory = resolve(options.directory);
  const protectedPaths = ["traicer.config.json", ".env.schema", ".env.local"];
  for (const relative of protectedPaths) {
    if (await exists(resolve(directory, relative))) {
      throw new Error(`Refusing to overwrite ${resolve(directory, relative)}`);
    }
  }

  const makeRandomBytes = dependencies.randomBytes ?? randomBytes;
  const makeUuid = dependencies.randomUuid ?? (() => crypto.randomUUID());
  const makeSigningKeys = dependencies.generateSigningKeyPair ?? generateDeviceSigningKeyPair;
  const deviceId = makeUuid();
  const signingKeys = await makeSigningKeys();
  const storage = resolveStorage(options, deviceId);
  const config: TraicerConfig = {
    capture: { adapters: [
      { allowedPaths: ["/v1/messages"], provider: "anthropic", upstreamOrigin: "https://api.anthropic.com" },
      { allowedPaths: ["/v1/chat/completions", "/v1/responses"], provider: "openai", upstreamOrigin: "https://api.openai.com" },
    ] },
    device: {
      id: deviceId,
      signerKeyId: signingKeys.keyId,
      signingPublicKey: signingKeys.publicKey,
    },
    marketplace: { apiBaseUrl: options.marketplaceApiBaseUrl },
    schema: "traicer.config/2",
    storage: {
      ...storage,
      bucketAlias: options.storage,
      prefix: "traices/",
      provider: options.storage,
    },
  };

  const localSecrets = await Promise.all([
    dependencies.encryptSecret(bytesToBase64Url(makeRandomBytes(32))),
    dependencies.encryptSecret(signingKeys.privateKey),
    dependencies.encryptSecret(bytesToBase64Url(makeRandomBytes(32))),
    dependencies.encryptSecret(bytesToBase64Url(makeRandomBytes(32))),
  ]);
  const localEnv = `# External credentials: fill these values, then run: traicer secrets --directory ${JSON.stringify(directory)}\nTRAICER_MARKETPLACE_CREDENTIAL=\nTRAICER_STORAGE_ACCESS_KEY_ID=\nTRAICER_STORAGE_SECRET_ACCESS_KEY=\nTRAICER_STORAGE_SESSION_TOKEN=\n\n# Device-local values are encrypted references; do not replace them with plaintext.\nTRAICER_CONTROL_TOKEN=${localSecrets[0]}\nTRAICER_SIGNING_PRIVATE_KEY=${localSecrets[1]}\nTRAICER_VAULT_KEY=${localSecrets[2]}\nTRAICER_PROJECT_MAPPING_KEY=${localSecrets[3]}\n`;

  await mkdir(directory, { recursive: true, mode: 0o700 });
  await Promise.all([
    writeFile(resolve(directory, "traicer.config.json"), `${JSON.stringify(config, null, 2)}\n`, { flag: "wx" }),
    writeFile(resolve(directory, ".env.schema"), envSchema, { flag: "wx" }),
    writeFile(resolve(directory, ".env.local"), localEnv, { flag: "wx", mode: 0o600 }),
    writeFile(resolve(directory, ".gitignore"), ".env.local\n.runtime.json\nproject-links.json\ntraicer-state.db*\n.alchemy/\ninfra/node_modules/\n", { flag: "a" }),
  ]);
  await chmod(resolve(directory, ".env.local"), 0o600);

  const stack = alchemyStack(options.storage, storage.bucket, options.accountId);
  if (!stack) return { config };
  const infrastructureDirectory = resolve(directory, "infra");
  await mkdir(infrastructureDirectory, { recursive: true });
  await Promise.all([
    writeFile(resolve(infrastructureDirectory, "package.json"), infraPackage, { flag: "wx" }),
    writeFile(resolve(infrastructureDirectory, "alchemy.run.ts"), stack, { flag: "wx" }),
    writeFile(resolve(infrastructureDirectory, "pnpm-workspace.yaml"), infraWorkspace, { flag: "wx" }),
  ]);
  return { config, infrastructureDirectory };
};

export const encryptWithVarlock = async (value: string): Promise<string> => {
  const child = Bun.spawn(varlockCommand("encrypt"), {
    stderr: "pipe",
    stdin: "pipe",
    stdout: "pipe",
  });
  child.stdin.write(value);
  child.stdin.end();
  const [exitCode, stdout, stderr] = await Promise.all([
    child.exited,
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
  ]);
  if (exitCode !== 0) throw new Error(`Varlock encryption failed: ${stderr.trim() || "unknown error"}`);
  const references = stdout.match(/varlock\("[^"\r\n]+"\)/g) ?? [];
  const reference = references.at(-1);
  if (!reference) throw new Error("Varlock returned no encrypted reference");
  return reference;
};
